project_id = "hrayem"

[db]
major_version = 17

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[functions.events]
verify_jwt = false

[functions.account]
verify_jwt = false

[functions.reports]
verify_jwt = false

[functions.share]
verify_jwt = false
